%% =========================================================================
% sum_sessions_effect_comparison.m
%
% Purpose:
% Summarize effect-comparison results across sessions.
%
% This script reads the per-session comparison_summary files generated by:
%   size_effect_comparation.m
%   contrast_effect_comparation.m
%
% It makes three summary figures:
%
%   Figure 1:
%       slope summary across sessions
%       Each comparison has one distribution per group.
%       Each point is one session.
%
%   Figure 2:
%       delta summary for baseline metric >= 0
%       Each comparison contains group blocks.
%       Within each group, each session is drawn separately.
%       Each distribution contains unit-level delta values.
%
%   Figure 3:
%       delta summary for baseline metric < 0
%       Same layout as Figure 2.
%
% Folder rule:
%
%   root_dir
%       session_folder
%           catgt_*
%               FA_Dlag_<data_content>
%                   mat_results
%                       runXXX
%                           size_effect_comparison_summary
%                           contrast_effect_comparison_summary
%
% For condition_specific_models:
%
%   root_dir
%       session_folder
%           catgt_*
%               size_effect_comparison_summary
%               contrast_effect_comparison_summary
%
% Session sorting:
%   The script sorts sessions by the number after "p" in the parent
%   session folder name.
%
% Example:
%   RafiL002p0119_g1 -> S1
%   RafiL001p0120_g1 -> S2
%
% The figure only shows S1, S2, ...
% The saved MultiSessionEffectComparison mat keeps the real folder mapping.
%
% Plot style:
%   'bar_points'
%       bar = mean
%       dots = individual values
%       black square = median
%
%   'violin'
%       violin = distribution
%       dots = individual values
%       black line = median
%       white diamond = mean
%
% Notes:
%   - R2 is read and stored in the output mat but not plotted.
%   - Delta plots use all valid unit-level delta values, not only central
%     points.
%   - Slope plot defaults to regression_central.slope.
%   - Delta plots can use a signed broken-axis display to keep extreme
%     points visible while improving central-region readability.
% =========================================================================

clc;
clear;

%% ========================== USER SETTINGS ==============================

root_dir = 'I:\np_data';

% -------------------------------------------------------------------------
% Effect type
% -------------------------------------------------------------------------
effect_type = 'contrast';
% Options:
% 'size'
% 'contrast'

% -------------------------------------------------------------------------
% Data content
% -------------------------------------------------------------------------
data_content = 'raw_count';
% Options:
% raw_count, raw_fr, z_within_trial, z_within_condition,
% z_across_conditions, demean_count_within_trial,
% demean_fr_within_trial, demean_pooledsd_within_condition

% -------------------------------------------------------------------------
% Model mode
% -------------------------------------------------------------------------
model_mode = 'all_condition_model';
% Options:
% 'all_condition_model'
% 'condition_specific_models'

runIdx = 1;

% Manual area labels in model-group order. They select the matching
% area-tagged upstream comparison files and label/save this summary. They do
% not determine unit membership and are not compared with any group-name
% field stored inside comparison_summary.
group_names = {'V1', 'MT'};

% -------------------------------------------------------------------------
% Size-only contrast filter
% -------------------------------------------------------------------------
pick_contrast = 0;
% Used only when effect_type = 'size'.
%
% Options:
% 0: all contrasts
% 1: low contrast only
% 2: high contrast only

% -------------------------------------------------------------------------
% Metric name
% -------------------------------------------------------------------------
metric_name = 'CMI';
%
% For effect_type = 'size':
%   'classic_SI'
%   'delta_SL'
%   'S_norm_diff'
%
% For effect_type = 'contrast':
%   'dHL'
%   'CMI'

% -------------------------------------------------------------------------
% Fields to summarize
% -------------------------------------------------------------------------
%
% Original data:
%   y
%
% Base noiseless reconstruction fields after data_reconstruction.m:
%   d
%   yRecon_use_across
%   yRecon_use_within
%   yRecon_use_all
%   yRecon_use_across_no_d
%   yRecon_use_within_no_d
%   yRecon_use_all_no_d
%   yRecon_across_excl_within
%   yRecon_within_excl_across
%
% Feedback / feedforward fields, if generated:
%   yRecon_use_feedback
%   yRecon_feedback_excl_within_ff_ambiguous
%   yRecon_feedback_excl_within
%   yRecon_feedback_excl_ff_ambiguous
%
%   yRecon_use_feedforward
%   yRecon_feedforward_excl_within_fb_ambiguous
%   yRecon_feedforward_excl_within
%   yRecon_feedforward_excl_fb_ambiguous
%
% Reconstruction fields with R noise, if generated:
%   yRecon_use_across_with_R
%   yRecon_use_within_with_R
%   yRecon_use_all_with_R
%   yRecon_across_excl_within_with_R
%   yRecon_within_excl_across_with_R
%
% Reconstruction fields keeping residual, if generated:
%   yRecon_use_across_keep_resid
%   yRecon_use_within_keep_resid
%   yRecon_use_all_keep_resid
%   yRecon_across_excl_within_keep_resid
%   yRecon_within_excl_across_keep_resid

% Baseline fields used on x-axis.
baseline_fields = {'yRecon_use_all'};

% Compared fields used on y-axis.
comparation_fields = { ...
    'yRecon_use_across', ...
    'yRecon_across_excl_within', ...
    'yRecon_use_within', ...
    'yRecon_within_excl_across'};

% -------------------------------------------------------------------------
% Time window selection
% -------------------------------------------------------------------------
time_selection_mode = 'full_trial';
% Options:
% 'full_trial'
% 'specific_window'
%
% For 'full_trial':
%   Select comparison_summary.is_full_trial_single_window == true.
%
% For 'specific_window':
%   Select a small-window result by target_analysis_window,
%   target_sliding_step, and target_time_window_index.

target_analysis_window = 0.2;
target_sliding_step = 0.2;
target_time_window_index = 2;

% -------------------------------------------------------------------------
% Slope summary setting
% -------------------------------------------------------------------------
regression_type_for_slope = 'central';
% Options:
% 'central'
% 'all'
%
% 'central':
%   Use comparison_summary.group(g).regression_central.slope.
%
% 'all':
%   Use comparison_summary.group(g).regression_all.slope.

% -------------------------------------------------------------------------
% Delta broken-axis display
% -------------------------------------------------------------------------
use_broken_axis_for_delta = true;
% true:
%   delta figures use a signed broken-axis display on the y-axis.
%   Extreme positive/negative deltas are still shown, but compressed.
%
% false:
%   delta figures use a normal linear y-axis.

delta_break_start_prctile = 97.0;
% Percentile of abs(delta values) used to start the broken tail.
% Smaller value compresses more points into the tail.
% Larger value keeps more points in the central linear region.

delta_broken_axis_trigger_ratio = 1;
% Broken-axis is used when:
%   raw_abs_max > break_start * delta_broken_axis_trigger_ratio
%
% 1 means use broken-axis whenever extremes exceed break_start.

delta_tail_display_frac = 0.10;
% Fraction of central half-axis used to display each compressed tail.

delta_break_gap_frac = 0.035;
% Visual gap between central region and compressed tail.

delta_min_tail_display_slope = 0.001;
% Minimum display slope in the compressed tail.
% Increase this if extreme tail points look too collapsed.

draw_delta_broken_axis_marks = true;

% -------------------------------------------------------------------------
% Save options
% -------------------------------------------------------------------------
save_mat = true;
save_fig = false;
save_png = true;
close_after_save = true;

% Print full MATLAB error report for skipped sessions.
print_full_error_report = false;

% -------------------------------------------------------------------------
% Plot options
% -------------------------------------------------------------------------
make_plots = true;
fig_visible = 'on';
% 'on' or 'off'

plot_style = 'bar_points';
% Options:
% 'bar_points'
% 'violin'
%
% File names include plot_style so bar and violin figures do not overwrite
% each other.

% Scatter point options.
point_size_slope = 36;
point_size_delta = 10;
point_alpha = 0.70;

% Bar + points mode.
bar_value_mode = 'median';
% options:
% 'mean'
% 'median'
%
% 'mean':
%   bar = mean
%   black square = median
%
% 'median':
%   bar = median
%   black square = mean

bar_alpha = 0.88;
show_summary_marker = true;
point_jitter_width_slope = 0.06;
point_jitter_width_delta = 0.10;

% Violin mode.
violin_alpha = 0.28;
show_mean_marker = true;
show_median_line = true;

% Figure options.
png_dpi = 400;

% Group colors, matched to the rest of your scripts.
group_colors_base = [ ...
    0.0000, 0.4470, 0.7410; ...
    0.8500, 0.3250, 0.0980];

% Session colors in delta plots are generated by making each group color
% progressively darker across S1, S2, ...
session_color_lightness_start = 0.65;
session_color_lightness_end = 0.05;

% Axis options.
draw_zero_line = true;
zero_line_style = 'k--';
zero_line_width = 1.0;

% X-axis layout.
% The script automatically adjusts item spacing and figure width based on
% the number of comparisons, groups, and sessions.
base_fig_height = 720;
slope_fig_width_min = 1000;
delta_fig_width_min = 1200;
max_fig_width = 4200;

%% ======================= VALIDATE SETTINGS =============================

validateUserSettings(effect_type, model_mode, metric_name, ...
    time_selection_mode, regression_type_for_slope, plot_style, ...
    bar_value_mode, pick_contrast);

baseline_fields = normalize_field_list_local(baseline_fields, 'baseline_fields');
comparation_fields = normalize_field_list_local(comparation_fields, 'comparation_fields');
group_names = normalizeManualGroupNamesLocal(group_names);
[group_display_names, group_file_tags, group_mapping_file_tag] = ...
    buildGroupLabelsLocal(group_names);

if ~(isnumeric(group_colors_base) && isreal(group_colors_base) && ...
        size(group_colors_base, 2) == 3 && ...
        all(isfinite(group_colors_base(:))) && ...
        all(group_colors_base(:) >= 0) && ...
        all(group_colors_base(:) <= 1))
    error('group_colors_base must be an N x 3 numeric matrix in [0, 1].');
end

effect_tag = makeEffectTag(effect_type);
model_tag = makeModelTag(model_mode);
metric_tag = makeMetricTag(effect_type, metric_name);
contrast_filter = buildContrastFilter(pick_contrast);

time_tag = makeTimeTag(time_selection_mode, ...
    target_analysis_window, target_sliding_step, target_time_window_index);

comparison_file_tag = makeComparisonSetFileTag(baseline_fields, comparation_fields);
delta_axis_file_tag = makeDeltaAxisFileTag(use_broken_axis_for_delta);

if strcmp(effect_type, 'size')
    out_base = sprintf('%s_%s_effectComp_%s_%s_%s_%s_%s_%s', ...
        data_content, effect_tag, model_tag, metric_tag, ...
        comparison_file_tag, contrast_filter.file_tag, ...
        group_mapping_file_tag, time_tag);
else
    out_base = sprintf('%s_%s_effectComp_%s_%s_%s_%s_%s', ...
        data_content, effect_tag, model_tag, metric_tag, ...
        comparison_file_tag, group_mapping_file_tag, time_tag);
end

summary_folder_name = getSummaryFolderName(effect_type);

fprintf('Root dir              : %s\n', root_dir);
fprintf('Effect type           : %s\n', effect_type);
fprintf('Data content          : %s\n', data_content);
fprintf('Model mode            : %s\n', model_mode);
fprintf('Run index             : %d\n', runIdx);
fprintf('Metric                : %s\n', metric_name);
fprintf('Comparison file tag   : %s\n', comparison_file_tag);
fprintf('Group-area mapping    : %s\n', group_mapping_file_tag);

if strcmp(effect_type, 'size')
    fprintf('Pick contrast         : %d (%s)\n', ...
        pick_contrast, contrast_filter.label);
end

fprintf('Time selection        : %s\n', time_selection_mode);

if strcmp(time_selection_mode, 'specific_window')
    fprintf('Target window         : analysis_window %.12g, step %.12g, window %d\n', ...
        target_analysis_window, target_sliding_step, target_time_window_index);
end

fprintf('Regression for slope  : %s\n', regression_type_for_slope);
fprintf('Plot style            : %s\n', plot_style);
fprintf('Delta axis            : %s\n', delta_axis_file_tag);
fprintf('Summary folder        : %s\n', summary_folder_name);
fprintf('Output base           : %s\n', out_base);

%% ======================= FIND SESSION FOLDERS ==========================

session_dirs = findCatgtSessionDirs(root_dir);

if isempty(session_dirs)
    error('No catgt_* folders found under one level below root_dir: %s', root_dir);
end

fprintf('\nFound %d candidate catgt_* session folders.\n', numel(session_dirs));

%% ======================= READ ALL SESSIONS =============================

records = {};
skipped = struct('session_dir', {}, 'reason', {});
ref = struct();

for si = 1:numel(session_dirs)
    session_dir = session_dirs{si};

    fprintf('\n[%d/%d] Reading %s\n', si, numel(session_dirs), session_dir);

    try
        [rec, ref] = readOneSessionEffectComparison( ...
            session_dir, ...
            effect_type, data_content, model_mode, runIdx, ...
            pick_contrast, contrast_filter, ...
            metric_name, ...
            baseline_fields, comparation_fields, ...
            time_selection_mode, ...
            target_analysis_window, target_sliding_step, ...
            target_time_window_index, ...
            summary_folder_name, ...
            group_mapping_file_tag, ...
            ref);

        records{end+1} = rec; %#ok<SAGROW>

    catch ME
        skipped(end+1).session_dir = session_dir; %#ok<SAGROW>
        skipped(end).reason = ME.message;

        warning('Skipping session: %s\nReason: %s', session_dir, ME.message);

        if print_full_error_report
            fprintf('\nFull error report for skipped session:\n');
            fprintf('%s\n', getReport(ME, 'extended', 'hyperlinks', 'off'));
        end
    end
end

if isempty(records)
    fprintf('\nSkipped sessions:\n');
    for k = 1:numel(skipped)
        fprintf('  %s\n    %s\n', skipped(k).session_dir, skipped(k).reason);
    end

    error('No valid sessions were loaded.');
end

fprintf('\nLoaded %d valid sessions.\n', numel(records));
fprintf('Skipped %d sessions.\n', numel(skipped));

if numel(group_names) ~= ref.nGroups
    error(['group_names contains %d labels, but the loaded comparison ' ...
           'results contain %d model groups.'], ...
          numel(group_names), ref.nGroups);
end

ref.group_names = group_names;
ref.group_display_names = group_display_names;
ref.group_file_tags = group_file_tags;
ref.group_mapping_file_tag = group_mapping_file_tag;

%% ======================= STACK VALUES ==================================

MultiSessionEffectComparison = buildMultiSessionEffectComparison( ...
    records, skipped, ref, root_dir, ...
    effect_type, data_content, model_mode, runIdx, ...
    pick_contrast, contrast_filter, metric_name, ...
    baseline_fields, comparation_fields, ...
    time_selection_mode, target_analysis_window, ...
    target_sliding_step, target_time_window_index, ...
    regression_type_for_slope, ...
    use_broken_axis_for_delta, ...
    delta_break_start_prctile, ...
    delta_broken_axis_trigger_ratio, ...
    delta_tail_display_frac, ...
    delta_break_gap_frac, ...
    delta_min_tail_display_slope, ...
    out_base);

if save_mat
    mat_file = fullfile(root_dir, [out_base '.mat']);
    save(mat_file, 'MultiSessionEffectComparison', '-v7.3');
    fprintf('\nSaved mat:\n  %s\n', mat_file);
end

%% ======================= PLOT ==========================================

if make_plots
    fig_handles = plotMultiSessionEffectComparison( ...
        MultiSessionEffectComparison, fig_visible, plot_style, ...
        group_colors_base, ...
        session_color_lightness_start, session_color_lightness_end, ...
        point_size_slope, point_size_delta, point_alpha, ...
        bar_alpha, bar_value_mode, show_summary_marker, ...
        point_jitter_width_slope, point_jitter_width_delta, ...
        violin_alpha, show_mean_marker, show_median_line, ...
        draw_zero_line, zero_line_style, zero_line_width, ...
        use_broken_axis_for_delta, ...
        delta_break_start_prctile, ...
        delta_broken_axis_trigger_ratio, ...
        delta_tail_display_frac, ...
        delta_break_gap_frac, ...
        delta_min_tail_display_slope, ...
        draw_delta_broken_axis_marks, ...
        slope_fig_width_min, delta_fig_width_min, ...
        base_fig_height, max_fig_width);

    if save_fig || save_png
        figure_tags = { ...
            'slope', ...
            ['delta_base_ge0_', delta_axis_file_tag], ...
            ['delta_base_lt0_', delta_axis_file_tag]};

        for f = 1:numel(fig_handles)
            if ~ishandle(fig_handles(f))
                continue;
            end

            plot_style_file_tag = makePlotStyleFileTag(plot_style, bar_value_mode);
            fig_base = sprintf('%s_%s_%s', out_base, plot_style_file_tag, figure_tags{f});

            if save_fig
                fig_file = fullfile(root_dir, [fig_base '.fig']);
                savefig(fig_handles(f), fig_file);
                fprintf('Saved FIG:\n  %s\n', fig_file);
            end

            if save_png
                png_file = fullfile(root_dir, [fig_base '.png']);
                savePngLocal(fig_handles(f), png_file, png_dpi);
                fprintf('Saved PNG:\n  %s\n', png_file);
            end
        end
    end

    if close_after_save
        close(fig_handles(ishandle(fig_handles)));
    end
end

fprintf('\nDone.\n');

%% ========================================================================
% Local functions
% ========================================================================

function validateUserSettings(effect_type, model_mode, metric_name, ...
    time_selection_mode, regression_type_for_slope, plot_style, ...
    bar_value_mode, pick_contrast)

valid_bar_value_mode = {'mean', 'median'};
assertStringOption(bar_value_mode, valid_bar_value_mode, 'bar_value_mode');

valid_effect = {'size', 'contrast'};
valid_model = {'all_condition_model', 'condition_specific_models'};
valid_time = {'full_trial', 'specific_window'};
valid_regression = {'central', 'all'};
valid_plot_style = {'bar_points', 'violin'};

assertStringOption(effect_type, valid_effect, 'effect_type');
assertStringOption(model_mode, valid_model, 'model_mode');
assertStringOption(time_selection_mode, valid_time, 'time_selection_mode');
assertStringOption(regression_type_for_slope, valid_regression, 'regression_type_for_slope');
assertStringOption(plot_style, valid_plot_style, 'plot_style');

switch char(effect_type)
    case 'size'
        valid_metric = {'classic_SI', 'delta_SL', 'S_norm_diff'};
        assertStringOption(metric_name, valid_metric, 'metric_name');

        if ~(isnumeric(pick_contrast) || islogical(pick_contrast)) || ...
                ~isscalar(pick_contrast) || ...
                ~ismember(double(pick_contrast), [0 1 2])
            error('For effect_type = size, pick_contrast must be 0, 1, or 2.');
        end

    case 'contrast'
        valid_metric = {'dHL', 'CMI'};
        assertStringOption(metric_name, valid_metric, 'metric_name');

    otherwise
        error('Unknown effect_type: %s', effect_type);
end
end

function assertStringOption(value, validOptions, varName)
if ~ischar(value) && ~isstring(value)
    error('%s must be a char or string.', varName);
end

value = char(value);

if ~any(strcmp(value, validOptions))
    error('%s = ''%s'' is invalid. Valid options are: %s', ...
        varName, value, strjoin(validOptions, ', '));
end
end

function fields = normalize_field_list_local(fields, var_name)
if ischar(fields)
    fields = {fields};
elseif isstring(fields)
    fields = cellstr(fields(:))';
elseif iscell(fields)
    fields = reshape(fields, 1, []);

    for i = 1:numel(fields)
        if isstring(fields{i})
            fields{i} = char(fields{i});
        end

        if ~ischar(fields{i})
            error('%s{%d} must be a char or string.', var_name, i);
        end
    end
else
    error('%s must be a char, string, string array, or cell array.', var_name);
end

if isempty(fields)
    error('%s is empty.', var_name);
end

empty_mask = cellfun(@isempty, fields);

if any(empty_mask)
    error('%s contains empty entries.', var_name);
end
end

function group_names = normalizeManualGroupNamesLocal(group_names)
if isempty(group_names)
    error(['group_names must be specified manually with one area label ' ...
           'for each model group.']);
end

if ischar(group_names)
    group_names = {group_names};
elseif isstring(group_names)
    group_names = cellstr(group_names(:))';
elseif iscell(group_names)
    group_names = reshape(group_names, 1, []);
else
    error('group_names must be a char, string array, or cell array.');
end

for g = 1:numel(group_names)
    if isstring(group_names{g}) && isscalar(group_names{g})
        group_names{g} = char(group_names{g});
    end

    if ~ischar(group_names{g})
        error('group_names{%d} must be a char or scalar string.', g);
    end

    group_names{g} = strtrim(group_names{g});

    if isempty(group_names{g})
        error('group_names{%d} is empty.', g);
    end
end
end

function [group_display_names, group_file_tags, group_mapping_file_tag] = ...
        buildGroupLabelsLocal(group_names)
nGroups = numel(group_names);
group_display_names = cell(1, nGroups);
group_file_tags = cell(1, nGroups);

for g = 1:nGroups
    group_display_names{g} = sprintf( ...
        'Group %d: %s', g, group_names{g});
    group_file_tags{g} = sprintf( ...
        'G%02d_%s', g, sanitizeGroupNameForFileLocal(group_names{g}));
end

group_mapping_file_tag = strjoin(group_file_tags, '_');
end

function name = sanitizeGroupNameForFileLocal(name)
if isstring(name)
    name = char(name);
end

name = regexprep(name, '[^a-zA-Z0-9_\-]', '_');
name = regexprep(name, '_+', '_');
name = strtrim(name);

if isempty(name)
    name = 'unnamed';
end
end

function tag = makeEffectTag(effect_type)
switch char(effect_type)
    case 'size'
        tag = 'size';

    case 'contrast'
        tag = 'contrast';

    otherwise
        error('Unknown effect_type: %s', effect_type);
end
end

function tag = makeModelTag(model_mode)
switch char(model_mode)
    case 'condition_specific_models'
        tag = 'condition_specific_M';

    case 'all_condition_model'
        tag = 'all_condition_M';

    otherwise
        error('Unknown model_mode: %s', model_mode);
end
end

function tag = makeMetricTag(effect_type, metric_name)
switch char(effect_type)
    case 'size'
        switch char(metric_name)
            case 'classic_SI'
                tag = 'SI';

            case 'delta_SL'
                tag = 'dSL';

            case 'S_norm_diff'
                tag = 'SnD';

            otherwise
                error('Unknown size metric_name: %s', metric_name);
        end

    case 'contrast'
        switch char(metric_name)
            case 'dHL'
                tag = 'dHL';

            case 'CMI'
                tag = 'CMI';

            otherwise
                error('Unknown contrast metric_name: %s', metric_name);
        end

    otherwise
        error('Unknown effect_type: %s', effect_type);
end
end

function contrast_filter = buildContrastFilter(pick_contrast)
pick_contrast = double(pick_contrast);

contrast_filter = struct();
contrast_filter.pick_contrast = pick_contrast;

switch pick_contrast
    case 0
        contrast_filter.label = 'all_contrasts';
        contrast_filter.file_suffix = '';
        contrast_filter.file_tag = 'allContrast';

    case 1
        contrast_filter.label = 'low_contrast';
        contrast_filter.file_suffix = '_low_contrast';
        contrast_filter.file_tag = 'lowContrast';

    case 2
        contrast_filter.label = 'high_contrast';
        contrast_filter.file_suffix = '_high_contrast';
        contrast_filter.file_tag = 'highContrast';

    otherwise
        error('pick_contrast must be 0, 1, or 2.');
end
end

function tag = makeTimeTag(time_selection_mode, analysis_window, sliding_step, window_index)
switch char(time_selection_mode)
    case 'full_trial'
        tag = 'fullTrial';

    case 'specific_window'
        tag = sprintf('wn%s_st%s_w%02d', ...
            formatSecondsForFileTag(analysis_window), ...
            formatSecondsForFileTag(sliding_step), ...
            window_index);

    otherwise
        error('Unknown time_selection_mode: %s', time_selection_mode);
end
end

function s = formatSecondsForFileTag(x)
s = sprintf('%.12g', x);
s = strrep(s, '.', '_');
s = strrep(s, '-', 'm');
s = regexprep(s, '[^a-zA-Z0-9_]', '_');
s = regexprep(s, '_+', '_');
end

function tag = makeComparisonSetFileTag(baseline_fields, comparation_fields)
nBase = numel(baseline_fields);
nComp = numel(comparation_fields);
parts = cell(1, nBase * nComp);
idx = 0;

for b = 1:nBase
    for c = 1:nComp
        idx = idx + 1;
        base_tag = analysisFieldToFileTagLocal(baseline_fields{b});
        comp_tag = analysisFieldToFileTagLocal(comparation_fields{c});
        parts{idx} = sprintf('%s_vs_%s', comp_tag, base_tag);
    end
end

tag = strjoin(parts, '__');
tag = makeSafeFileTagLocal(tag);
end

function tag = analysisFieldToFileTagLocal(field_name)
switch char(field_name)
    case 'y'
        tag = 'y';

    case 'd'
        tag = 'd';

    case 'yRecon_use_all'
        tag = 'all';

    case 'yRecon_use_all_no_d'
        tag = 'all_no_d';

    case 'yRecon_use_across'
        tag = 'acr';

    case 'yRecon_use_across_no_d'
        tag = 'acr_no_d';

    case 'yRecon_use_within'
        tag = 'win';

    case 'yRecon_use_within_no_d'
        tag = 'win_no_d';

    case 'yRecon_across_excl_within'
        tag = 'acr_excl_win';

    case 'yRecon_within_excl_across'
        tag = 'win_excl_acr';

    case 'yRecon_use_feedback'
        tag = 'fb';

    case 'yRecon_feedback_excl_within_ff_ambiguous'
        tag = 'fb_excl_win_ff_amb';

    case 'yRecon_feedback_excl_within'
        tag = 'fb_excl_win';

    case 'yRecon_feedback_excl_ff_ambiguous'
        tag = 'fb_excl_ff_amb';

    case 'yRecon_use_feedforward'
        tag = 'ff';

    case 'yRecon_feedforward_excl_within_fb_ambiguous'
        tag = 'ff_excl_win_fb_amb';

    case 'yRecon_feedforward_excl_within'
        tag = 'ff_excl_win';

    case 'yRecon_feedforward_excl_fb_ambiguous'
        tag = 'ff_excl_fb_amb';

    case 'yRecon_use_all_with_R'
        tag = 'all_R';

    case 'yRecon_use_across_with_R'
        tag = 'acr_R';

    case 'yRecon_use_within_with_R'
        tag = 'win_R';

    case 'yRecon_across_excl_within_with_R'
        tag = 'acr_excl_win_R';

    case 'yRecon_within_excl_across_with_R'
        tag = 'win_excl_acr_R';

    case 'yRecon_use_all_keep_resid'
        tag = 'all_KR';

    case 'yRecon_use_across_keep_resid'
        tag = 'acr_KR';

    case 'yRecon_use_within_keep_resid'
        tag = 'win_KR';

    case 'yRecon_across_excl_within_keep_resid'
        tag = 'acr_excl_win_KR';

    case 'yRecon_within_excl_across_keep_resid'
        tag = 'win_excl_acr_KR';

    otherwise
        tag = fallbackShortFieldLabel(field_name);
        tag = makeSafeFileTagLocal(tag);
end
end

function tag = makePlotStyleFileTag(plot_style, bar_value_mode)
switch char(plot_style)
    case 'bar_points'
        tag = sprintf('bar_points_barAs%s', char(bar_value_mode));

    case 'violin'
        tag = 'violin';

    otherwise
        tag = makeSafeFileTagLocal(plot_style);
end
end

function tag = makeSafeFileTagLocal(x)
tag = char(x);
tag = strtrim(tag);
tag = strrep(tag, ' ', '_');
tag = strrep(tag, '-', '_');
tag = strrep(tag, '/', '_');
tag = strrep(tag, '\', '_');
tag = regexprep(tag, '[^a-zA-Z0-9_]', '_');
tag = regexprep(tag, '_+', '_');
tag = regexprep(tag, '^_+', '');
tag = regexprep(tag, '_+$', '');

if isempty(tag)
    tag = 'untitled';
end
end

function tag = makeDeltaAxisFileTag(use_broken_axis_for_delta)
if use_broken_axis_for_delta
    tag = 'deltaBroken';
else
    tag = 'deltaLinear';
end
end

function folder_name = getSummaryFolderName(effect_type)
switch char(effect_type)
    case 'size'
        folder_name = 'size_effect_comparison_summary';

    case 'contrast'
        folder_name = 'contrast_effect_comparison_summary';

    otherwise
        error('Unknown effect_type: %s', effect_type);
end
end

function tf = filenameHasExactGroupMappingLocal(filename, group_mapping_file_tag)
[~, stem, extension] = fileparts(filename);

if ~strcmpi(extension, '.mat')
    tf = false;
    return;
end

escaped_tag = regexptranslate('escape', group_mapping_file_tag);
expression = ['_', escaped_tag, '(_wn.*_w[0-9]+)?$'];
tf = ~isempty(regexp(stem, expression, 'once'));
end

function session_dirs = findCatgtSessionDirs(root_dir)
listing = dir(fullfile(root_dir, '*', 'catgt_*'));
listing = listing([listing.isdir]);

if isempty(listing)
    session_dirs = {};
    return;
end

session_dirs = cell(1, numel(listing));
sort_keys = nan(1, numel(listing));
name_keys = cell(1, numel(listing));

for k = 1:numel(listing)
    session_dirs{k} = fullfile(listing(k).folder, listing(k).name);

    [parent_dir, ~] = fileparts(session_dirs{k});
    [~, parent_name] = fileparts(parent_dir);

    sort_keys(k) = extractSessionNumberFromName(parent_name);
    name_keys{k} = parent_name;
end

T = table(sort_keys(:), name_keys(:), session_dirs(:), ...
    'VariableNames', {'session_number', 'session_name', 'session_dir'});

T = sortrows(T, {'session_number', 'session_name'});
session_dirs = T.session_dir(:)';
end

function session_number = extractSessionNumberFromName(session_name)
tokens = regexp(session_name, 'p(\d+)', 'tokens', 'once');

if isempty(tokens)
    session_number = inf;
else
    session_number = str2double(tokens{1});

    if ~isfinite(session_number)
        session_number = inf;
    end
end
end

function [rec, ref] = readOneSessionEffectComparison( ...
    session_dir, ...
    effect_type, data_content, model_mode, runIdx, ...
    pick_contrast, contrast_filter, metric_name, ...
    baseline_fields, comparation_fields, ...
    time_selection_mode, ...
    target_analysis_window, target_sliding_step, target_time_window_index, ...
    summary_folder_name, group_mapping_file_tag, ref)

summary_dir = getSummaryDirForSession(session_dir, data_content, model_mode, ...
    runIdx, summary_folder_name);

if ~exist(summary_dir, 'dir')
    error('Summary folder not found: %s', summary_dir);
end

summary_files = dir(fullfile(summary_dir, '*.mat'));

if isempty(summary_files)
    error('No summary mat files found in: %s', summary_dir);
end

mapping_mask = arrayfun( ...
    @(x) filenameHasExactGroupMappingLocal( ...
        x.name, group_mapping_file_tag), ...
    summary_files);
summary_files = summary_files(mapping_mask);

if isempty(summary_files)
    error(['No comparison-summary MAT filename in %s contains the exact ' ...
           'group mapping %s.'], ...
          summary_dir, group_mapping_file_tag);
end

comparison_list = buildComparisonList(baseline_fields, comparation_fields);
loaded_summaries = loadAllComparisonSummaries(summary_dir, summary_files);

rec = struct();
rec.session_dir = session_dir;
rec.session_name = getSessionName(session_dir);
rec.session_parent_name = getSessionParentName(session_dir);
rec.session_number = extractSessionNumberFromName(rec.session_parent_name);
rec.summary_dir = summary_dir;
rec.comparison = repmat(struct(), 1, numel(comparison_list));

for c = 1:numel(comparison_list)
    target_base = comparison_list(c).baseline_field;
    target_comp = comparison_list(c).comparation_field;

    [summary, summary_file] = findMatchingComparisonSummary( ...
        loaded_summaries, ...
        effect_type, data_content, model_mode, runIdx, ...
        pick_contrast, contrast_filter, metric_name, ...
        target_base, target_comp, ...
        time_selection_mode, ...
        target_analysis_window, target_sliding_step, target_time_window_index);

    validateComparisonSummaryForUse(summary, effect_type, metric_name, ...
        target_base, target_comp, summary_file);

    rec.comparison(c).comparison_index = c;
    rec.comparison(c).baseline_field = target_base;
    rec.comparison(c).comparation_field = target_comp;
    rec.comparison(c).comparison_label = makeComparisonLabel(target_base, target_comp);
    rec.comparison(c).summary_file = summary_file;
    rec.comparison(c).summary = summary;
end

ref = updateAndCheckEffectReference(ref, rec, comparison_list, session_dir);
end

function summary_dir = getSummaryDirForSession(session_dir, data_content, model_mode, ...
    runIdx, summary_folder_name)

switch char(model_mode)
    case 'all_condition_model'
        summary_dir = fullfile(session_dir, sprintf('FA_Dlag_%s', data_content), ...
            'mat_results', sprintf('run%03d', runIdx), summary_folder_name);

    case 'condition_specific_models'
        summary_dir = fullfile(session_dir, summary_folder_name);

    otherwise
        error('Unknown model_mode: %s', model_mode);
end
end

function comparison_list = buildComparisonList(baseline_fields, comparation_fields)
nBase = numel(baseline_fields);
nComp = numel(comparation_fields);

comparison_list = repmat(struct( ...
    'comparison_index', [], ...
    'baseline_field', '', ...
    'comparation_field', '', ...
    'comparison_label', ''), 1, nBase * nComp);

idx = 0;

for b = 1:nBase
    for c = 1:nComp
        idx = idx + 1;

        comparison_list(idx).comparison_index = idx;
        comparison_list(idx).baseline_field = baseline_fields{b};
        comparison_list(idx).comparation_field = comparation_fields{c};
        comparison_list(idx).comparison_label = makeComparisonLabel( ...
            baseline_fields{b}, comparation_fields{c});
    end
end
end

function loaded = loadAllComparisonSummaries(summary_dir, summary_files)
loaded = repmat(struct( ...
    'file', '', ...
    'comparison_summary', []), 1, numel(summary_files));

for i = 1:numel(summary_files)
    this_file = fullfile(summary_dir, summary_files(i).name);
    S = load(this_file);

    if ~isfield(S, 'comparison_summary')
        loaded(i).file = this_file;
        loaded(i).comparison_summary = [];
        continue;
    end

    loaded(i).file = this_file;
    loaded(i).comparison_summary = S.comparison_summary;
end
end

function [summary, summary_file] = findMatchingComparisonSummary( ...
    loaded_summaries, ...
    effect_type, data_content, model_mode, runIdx, ...
    pick_contrast, contrast_filter, metric_name, ...
    baseline_field, comparation_field, ...
    time_selection_mode, ...
    target_analysis_window, target_sliding_step, target_time_window_index)

match_idx = false(1, numel(loaded_summaries));

for i = 1:numel(loaded_summaries)
    S = loaded_summaries(i).comparison_summary;

    if isempty(S)
        continue;
    end

    if summaryMatchesTarget(S, effect_type, data_content, model_mode, runIdx, ...
            pick_contrast, contrast_filter, metric_name, ...
            baseline_field, comparation_field, ...
            time_selection_mode, ...
            target_analysis_window, target_sliding_step, target_time_window_index)
        match_idx(i) = true;
    end
end

idx = find(match_idx);

if isempty(idx)
    error(['No matching comparison_summary found for:\n', ...
        '  metric: %s\n', ...
        '  baseline: %s\n', ...
        '  compared: %s'], ...
        metric_name, baseline_field, comparation_field);
end

if numel(idx) > 1
    fprintf('\nMatched files:\n');
    for k = 1:numel(idx)
        fprintf('  %s\n', loaded_summaries(idx(k)).file);
    end

    error(['More than one matching comparison_summary found for ', ...
        '%s vs %s. Make the time/metric/contrast selection more specific.'], ...
        comparation_field, baseline_field);
end

summary = loaded_summaries(idx).comparison_summary;
summary_file = loaded_summaries(idx).file;
end

function tf = summaryMatchesTarget(S, effect_type, data_content, model_mode, runIdx, ...
    pick_contrast, contrast_filter, metric_name, ...
    baseline_field, comparation_field, ...
    time_selection_mode, ...
    target_analysis_window, target_sliding_step, target_time_window_index)

tf = true;

tf = tf && isfield(S, 'effect_type') && strcmp(char(S.effect_type), char(effect_type));
tf = tf && isfield(S, 'data_content') && strcmp(char(S.data_content), char(data_content));
tf = tf && isfield(S, 'model_mode') && strcmp(char(S.model_mode), char(model_mode));
tf = tf && isfield(S, 'metric_name') && strcmp(char(S.metric_name), char(metric_name));
tf = tf && isfield(S, 'baseline_field') && strcmp(char(S.baseline_field), char(baseline_field));
tf = tf && isfield(S, 'comparation_field') && strcmp(char(S.comparation_field), char(comparation_field));

if isfield(S, 'runIdx')
    tf = tf && isequal(double(S.runIdx), double(runIdx));
end

if strcmp(effect_type, 'size')
    tf = tf && isfield(S, 'pick_contrast') && ...
        isequal(double(S.pick_contrast), double(pick_contrast));

    if isfield(S, 'contrast_label')
        tf = tf && strcmp(char(S.contrast_label), contrast_filter.label);
    end
end

tf = tf && timeInfoMatchesTarget(S, time_selection_mode, ...
    target_analysis_window, target_sliding_step, target_time_window_index);
end

function tf = timeInfoMatchesTarget(S, time_selection_mode, ...
    target_analysis_window, target_sliding_step, target_time_window_index)

required_fields = { ...
    'is_full_trial_single_window', ...
    'analysis_window', ...
    'sliding_step', ...
    'time_window_index'};

for i = 1:numel(required_fields)
    if ~isfield(S, required_fields{i})
        tf = false;
        return;
    end
end

tol = 1e-10;

switch char(time_selection_mode)
    case 'full_trial'
        tf = logical(S.is_full_trial_single_window);

    case 'specific_window'
        tf = ~logical(S.is_full_trial_single_window) && ...
            abs(double(S.analysis_window) - target_analysis_window) <= tol && ...
            abs(double(S.sliding_step) - target_sliding_step) <= tol && ...
            double(S.time_window_index) == double(target_time_window_index);

    otherwise
        error('Unknown time_selection_mode: %s', time_selection_mode);
end
end

function validateComparisonSummaryForUse(S, effect_type, metric_name, ...
    baseline_field, comparation_field, summary_file)

required_fields = { ...
    'effect_type', ...
    'metric_name', ...
    'baseline_field', ...
    'comparation_field', ...
    'group', ...
    'groupd', ...
    'analysis_window', ...
    'sliding_step', ...
    'time_window_index', ...
    'is_full_trial_single_window'};

for i = 1:numel(required_fields)
    if ~isfield(S, required_fields{i})
        error('comparison_summary in %s is missing field %s.', ...
            summary_file, required_fields{i});
    end
end

if ~strcmp(char(S.effect_type), char(effect_type))
    error('Effect type mismatch in %s.', summary_file);
end

if ~strcmp(char(S.metric_name), char(metric_name))
    error('Metric name mismatch in %s.', summary_file);
end

if ~strcmp(char(S.baseline_field), char(baseline_field)) || ...
        ~strcmp(char(S.comparation_field), char(comparation_field))
    error('Field comparison mismatch in %s.', summary_file);
end

groupd = double(S.groupd(:)');

if isempty(groupd) || any(~isfinite(groupd)) || ...
        any(groupd <= 0) || any(groupd ~= round(groupd))
    error('groupd in %s must contain finite positive integers.', summary_file);
end

if numel(S.group) ~= numel(groupd)
    error(['comparison_summary in %s contains %d group structures, but ' ...
           'groupd contains %d entries.'], ...
          summary_file, numel(S.group), numel(groupd));
end

for g = 1:numel(S.group)
    if ~isfield(S.group(g), 'regression_all')
        error('summary.group(%d).regression_all missing in %s.', g, summary_file);
    end

    if ~isfield(S.group(g), 'regression_central')
        error('summary.group(%d).regression_central missing in %s.', g, summary_file);
    end

    if ~isfield(S.group(g), 'delta_by_base_sign') || ...
            ~isfield(S.group(g).delta_by_base_sign, 'positive_base') || ...
            ~isfield(S.group(g).delta_by_base_sign, 'negative_base')
        error('summary.group(%d).delta_by_base_sign missing in %s.', g, summary_file);
    end
end
end

function ref = updateAndCheckEffectReference(ref, rec, comparison_list, session_dir)
first_summary = rec.comparison(1).summary;

nGroups = numel(first_summary.group);
reference_groupd = double(first_summary.groupd(:)');

for c = 2:numel(rec.comparison)
    current_summary = rec.comparison(c).summary;
    current_nGroups = numel(current_summary.group);
    current_groupd = double(current_summary.groupd(:)');

    if current_nGroups ~= nGroups
        error(['Comparison %d in %s contains %d groups, but comparison 1 ' ...
               'contains %d groups.'], ...
              c, session_dir, current_nGroups, nGroups);
    end

    if ~isequal(current_groupd, reference_groupd)
        error(['groupd mismatch between comparison 1 and comparison %d ' ...
               'within %s.'], c, session_dir);
    end
end

if isempty(fieldnames(ref))
    ref.nGroups = nGroups;
    ref.comparison_list = comparison_list;
    return;
end

if ref.nGroups ~= nGroups
    error('Number of groups mismatch in %s. Got %d, expected %d.', ...
        session_dir, nGroups, ref.nGroups);
end

% Important:
% Different sessions can have different numbers of units in each group.
% This is expected. Only the number of groups must match across sessions.

if numel(ref.comparison_list) ~= numel(comparison_list)
    error('Number of comparisons mismatch in %s.', session_dir);
end

for c = 1:numel(comparison_list)
    if ~strcmp(ref.comparison_list(c).baseline_field, comparison_list(c).baseline_field) || ...
            ~strcmp(ref.comparison_list(c).comparation_field, comparison_list(c).comparation_field)
        error('Comparison list mismatch in %s.', session_dir);
    end
end
end

function name = getSessionName(session_dir)
[parent_dir, catgt_name] = fileparts(session_dir);
[~, parent_name] = fileparts(parent_dir);
name = sprintf('%s/%s', parent_name, catgt_name);
end

function parent_name = getSessionParentName(session_dir)
[parent_dir, ~] = fileparts(session_dir);
[~, parent_name] = fileparts(parent_dir);
end

function M = buildMultiSessionEffectComparison( ...
    records, skipped, ref, root_dir, ...
    effect_type, data_content, model_mode, runIdx, ...
    pick_contrast, contrast_filter, metric_name, ...
    baseline_fields, comparation_fields, ...
    time_selection_mode, target_analysis_window, ...
    target_sliding_step, target_time_window_index, ...
    regression_type_for_slope, ...
    use_broken_axis_for_delta, ...
    delta_break_start_prctile, ...
    delta_broken_axis_trigger_ratio, ...
    delta_tail_display_frac, ...
    delta_break_gap_frac, ...
    delta_min_tail_display_slope, ...
    out_base)

nSessions = numel(records);
nComparisons = numel(ref.comparison_list);
nGroups = ref.nGroups;

session_info = struct( ...
    'session_index', {}, ...
    'session_label', {}, ...
    'session_name', {}, ...
    'session_parent_name', {}, ...
    'session_number', {}, ...
    'session_dir', {}, ...
    'summary_dir', {}, ...
    'groupd', {});

for s = 1:nSessions
    session_info(s).session_index = s;
    session_info(s).session_label = sprintf('S%d', s);
    session_info(s).session_name = records{s}.session_name;
    session_info(s).session_parent_name = records{s}.session_parent_name;
    session_info(s).session_number = records{s}.session_number;
    session_info(s).session_dir = records{s}.session_dir;
    session_info(s).summary_dir = records{s}.summary_dir;
    session_info(s).groupd = records{s}.comparison(1).summary.groupd;
end

comparison_info = struct( ...
    'comparison_index', {}, ...
    'baseline_field', {}, ...
    'comparation_field', {}, ...
    'comparison_label', {});

for c = 1:nComparisons
    comparison_info(c).comparison_index = c;
    comparison_info(c).baseline_field = ref.comparison_list(c).baseline_field;
    comparison_info(c).comparation_field = ref.comparison_list(c).comparation_field;
    comparison_info(c).comparison_label = makeComparisonLabel( ...
        ref.comparison_list(c).baseline_field, ...
        ref.comparison_list(c).comparation_field);
end

slope_all = nan(nSessions, nComparisons, nGroups);
slope_central = nan(nSessions, nComparisons, nGroups);
R2_all = nan(nSessions, nComparisons, nGroups);
R2_central = nan(nSessions, nComparisons, nGroups);

delta_positive = cell(nSessions, nComparisons, nGroups);
delta_negative = cell(nSessions, nComparisons, nGroups);

summary_file = cell(nSessions, nComparisons);

for s = 1:nSessions
    for c = 1:nComparisons
        S = records{s}.comparison(c).summary;
        summary_file{s, c} = records{s}.comparison(c).summary_file;

        for g = 1:nGroups
            reg_all = S.group(g).regression_all;
            reg_central = S.group(g).regression_central;

            slope_all(s, c, g) = getRegressionFieldValue(reg_all, 'slope');
            slope_central(s, c, g) = getRegressionFieldValue(reg_central, 'slope');

            R2_all(s, c, g) = getRegressionFieldValue(reg_all, 'R2');
            R2_central(s, c, g) = getRegressionFieldValue(reg_central, 'R2');

            delta_positive{s, c, g} = getDeltaValuesFromSplit( ...
                S.group(g).delta_by_base_sign.positive_base);

            delta_negative{s, c, g} = getDeltaValuesFromSplit( ...
                S.group(g).delta_by_base_sign.negative_base);
        end
    end
end

switch char(regression_type_for_slope)
    case 'central'
        slope_for_plot = slope_central;
        R2_for_slope = R2_central;

    case 'all'
        slope_for_plot = slope_all;
        R2_for_slope = R2_all;

    otherwise
        error('Unknown regression_type_for_slope: %s', regression_type_for_slope);
end

M = struct();

M.meta.root_dir = root_dir;
M.meta.effect_type = effect_type;
M.meta.data_content = data_content;
M.meta.model_mode = model_mode;
M.meta.runIdx = runIdx;
M.meta.pick_contrast = pick_contrast;
M.meta.contrast_label = contrast_filter.label;
M.meta.metric_name = metric_name;
M.meta.time_selection_mode = time_selection_mode;
M.meta.target_analysis_window = target_analysis_window;
M.meta.target_sliding_step = target_sliding_step;
M.meta.target_time_window_index = target_time_window_index;
M.meta.regression_type_for_slope = regression_type_for_slope;
M.meta.use_broken_axis_for_delta = use_broken_axis_for_delta;
M.meta.delta_break_start_prctile = delta_break_start_prctile;
M.meta.delta_broken_axis_trigger_ratio = delta_broken_axis_trigger_ratio;
M.meta.delta_tail_display_frac = delta_tail_display_frac;
M.meta.delta_break_gap_frac = delta_break_gap_frac;
M.meta.delta_min_tail_display_slope = delta_min_tail_display_slope;
M.meta.output_base = out_base;
M.meta.comparison_file_tag = makeComparisonSetFileTag(baseline_fields, comparation_fields);
M.meta.num_sessions = nSessions;
M.meta.num_comparisons = nComparisons;
M.meta.num_groups = nGroups;
M.meta.group_mapping_file_tag = ref.group_mapping_file_tag;
M.meta.group_label_source = 'manual group_names parameter';

M.settings.baseline_fields = baseline_fields;
M.settings.comparation_fields = comparation_fields;

M.labels.group_names = ref.group_names;
M.labels.group_display_names = ref.group_display_names;
M.labels.group_file_tags = ref.group_file_tags;
M.labels.group_mapping_file_tag = ref.group_mapping_file_tag;
M.labels.group_short = ref.group_file_tags;
M.labels.comparison = {comparison_info.comparison_label};
M.labels.session = {session_info.session_label};

M.sessions.included = session_info;
M.sessions.skipped = skipped;

M.comparisons = comparison_info;
M.summary_file = summary_file;

M.values.slope_all = slope_all;
M.values.slope_central = slope_central;
M.values.slope_for_plot = slope_for_plot;

M.values.R2_all = R2_all;
M.values.R2_central = R2_central;
M.values.R2_for_slope = R2_for_slope;

M.values.delta_positive_base = delta_positive;
M.values.delta_negative_base = delta_negative;

M.dimension_names.slope = {'session', 'comparison', 'group'};
M.dimension_names.delta = {'session', 'comparison', 'group'};

M.notes.delta_definition = 'delta = compared metric - baseline metric';
M.notes.delta_positive_base = 'baseline metric >= 0';
M.notes.delta_negative_base = 'baseline metric < 0';
M.notes.slope_default = ...
    'slope_for_plot uses regression_type_for_slope, default central';
M.notes.groupd = ...
    'groupd can differ across sessions; each session groupd is saved in sessions.included(s).groupd';
end

function v = getRegressionFieldValue(reg, field_name)
if isfield(reg, field_name)
    v = reg.(field_name);
else
    v = NaN;
end

if isempty(v) || ~isscalar(v) || ~isnumeric(v)
    v = NaN;
end
end

function vals = getDeltaValuesFromSplit(split_summary)
if isfield(split_summary, 'delta_values')
    vals = split_summary.delta_values(:);
else
    vals = [];
end

vals = vals(isfinite(vals));
end

function labels = makeGroupShortLabels(nGroups)
labels = cell(1, nGroups);

for g = 1:nGroups
    labels{g} = sprintf('G%d', g);
end
end

function fig_handles = plotMultiSessionEffectComparison( ...
    M, fig_visible, plot_style, ...
    group_colors_base, ...
    session_color_lightness_start, session_color_lightness_end, ...
    point_size_slope, point_size_delta, point_alpha, ...
    bar_alpha, bar_value_mode, show_summary_marker, ...
    point_jitter_width_slope, point_jitter_width_delta, ...
    violin_alpha, show_mean_marker, show_median_line, ...
    draw_zero_line, zero_line_style, zero_line_width, ...
    use_broken_axis_for_delta, ...
    delta_break_start_prctile, ...
    delta_broken_axis_trigger_ratio, ...
    delta_tail_display_frac, ...
    delta_break_gap_frac, ...
    delta_min_tail_display_slope, ...
    draw_delta_broken_axis_marks, ...
    slope_fig_width_min, delta_fig_width_min, ...
    base_fig_height, max_fig_width)

fig_handles = gobjects(1, 3);

fig_handles(1) = plotSlopeSummary( ...
    M, fig_visible, plot_style, group_colors_base, ...
    point_size_slope, point_alpha, ...
    bar_alpha, bar_value_mode, show_summary_marker, point_jitter_width_slope, ...
    violin_alpha, show_mean_marker, show_median_line, ...
    draw_zero_line, zero_line_style, zero_line_width, ...
    slope_fig_width_min, base_fig_height, max_fig_width);

fig_handles(2) = plotDeltaSummary( ...
    M, fig_visible, plot_style, group_colors_base, ...
    session_color_lightness_start, session_color_lightness_end, ...
    'positive', ...
    point_size_delta, point_alpha, ...
    bar_alpha, bar_value_mode, show_summary_marker, point_jitter_width_delta, ...
    violin_alpha, show_mean_marker, show_median_line, ...
    draw_zero_line, zero_line_style, zero_line_width, ...
    use_broken_axis_for_delta, ...
    delta_break_start_prctile, ...
    delta_broken_axis_trigger_ratio, ...
    delta_tail_display_frac, ...
    delta_break_gap_frac, ...
    delta_min_tail_display_slope, ...
    draw_delta_broken_axis_marks, ...
    delta_fig_width_min, base_fig_height, max_fig_width);

fig_handles(3) = plotDeltaSummary( ...
    M, fig_visible, plot_style, group_colors_base, ...
    session_color_lightness_start, session_color_lightness_end, ...
    'negative', ...
    point_size_delta, point_alpha, ...
    bar_alpha, bar_value_mode, show_summary_marker, point_jitter_width_delta, ...
    violin_alpha, show_mean_marker, show_median_line, ...
    draw_zero_line, zero_line_style, zero_line_width, ...
    use_broken_axis_for_delta, ...
    delta_break_start_prctile, ...
    delta_broken_axis_trigger_ratio, ...
    delta_tail_display_frac, ...
    delta_break_gap_frac, ...
    delta_min_tail_display_slope, ...
    draw_delta_broken_axis_marks, ...
    delta_fig_width_min, base_fig_height, max_fig_width);
end

function hfig = plotSlopeSummary( ...
    M, fig_visible, plot_style, group_colors_base, ...
    point_size, point_alpha, ...
    bar_alpha, bar_value_mode, show_summary_marker, point_jitter_width, ...
    violin_alpha, show_mean_marker, show_median_line, ...
    draw_zero_line, zero_line_style, zero_line_width, ...
    fig_width_min, fig_height, max_fig_width)

values = M.values.slope_for_plot;

nComparisons = size(values, 2);
nGroups = size(values, 3);

layout = computeSlopeLayout(nComparisons, nGroups);

fig_width = min(max_fig_width, max(fig_width_min, 260 * nComparisons + 220));

hfig = figure('Visible', fig_visible, ...
    'Color', 'w', ...
    'Position', [100 100 fig_width fig_height], ...
    'Name', 'Session slope summary');

ax = axes(hfig);
hold(ax, 'on');

set(ax, 'Units', 'normalized');
set(ax, 'Position', [0.07 0.20 0.80 0.70]);

group_colors = resolveGroupColors(group_colors_base, nGroups);

bar_width = computeAdaptiveItemWidth(nComparisons * nGroups, 0.25, 0.55);
violin_width = computeAdaptiveItemWidth(nComparisons * nGroups, 0.18, 0.42);

axis_info_linear = makeLinearAxisInfo();

for c = 1:nComparisons
    for g = 1:nGroups
        x0 = layout.group_x(c, g);
        y = squeeze(values(:, c, g));
        color = group_colors(g, :);

        switch char(plot_style)
            case 'bar_points'
                drawBarWithPoints(ax, x0, y, bar_width, color, ...
                    point_size, point_alpha, bar_alpha, ...
                    point_jitter_width, bar_value_mode, show_summary_marker, axis_info_linear);

            case 'violin'
                drawViolinWithPoints(ax, x0, y, violin_width, color, ...
                    point_size, point_alpha, violin_alpha, ...
                    show_mean_marker, show_median_line, axis_info_linear);

            otherwise
                error('Unknown plot_style: %s', plot_style);
        end
    end
end

if draw_zero_line
    yline(ax, 0, zero_line_style, ...
        'LineWidth', zero_line_width, ...
        'HandleVisibility', 'off');
end

applySlopeAxisFormatting(ax, M, layout, values);

dummy = gobjects(1, nGroups);
for g = 1:nGroups
    dummy(g) = plot(ax, nan, nan, 'o', ...
        'MarkerFaceColor', group_colors(g, :), ...
        'MarkerEdgeColor', group_colors(g, :), ...
        'LineStyle', 'none', ...
        'MarkerSize', 7);
end

legend(ax, dummy, M.labels.group_display_names, ...
    'Location', 'eastoutside', ...
    'Interpreter', 'none', ...
    'Box', 'off');

title(ax, sprintf('%s | %s | %s | %s slope (%s regression)', ...
    M.meta.effect_type, M.meta.data_content, M.meta.model_mode, ...
    M.meta.metric_name, M.meta.regression_type_for_slope), ...
    'Interpreter', 'none', ...
    'FontWeight', 'bold');

ylabel(ax, sprintf('Slope (%s)', M.meta.regression_type_for_slope), ...
    'Interpreter', 'none');

xlabel(ax, 'Comparison', 'Interpreter', 'none');
cleanAxis(ax);
end

function layout = computeSlopeLayout(nComparisons, nGroups)
group_step = 0.82;
comparison_gap = 1.05;

group_x = nan(nComparisons, nGroups);
comparison_center = nan(1, nComparisons);
separator_x = nan(1, max(0, nComparisons - 1));

x = 1;

for c = 1:nComparisons
    first_x = x;

    for g = 1:nGroups
        group_x(c, g) = x;
        x = x + group_step;
    end

    last_x = group_x(c, nGroups);
    comparison_center(c) = mean([first_x, last_x]);

    if c < nComparisons
        separator_x(c) = last_x + comparison_gap / 2;
    end

    x = x + comparison_gap;
end

layout.group_x = group_x;
layout.comparison_center = comparison_center;
layout.separator_x = separator_x;
layout.x_min = min(group_x(:)) - 0.7;
layout.x_max = max(group_x(:)) + 0.7;
end

function applySlopeAxisFormatting(ax, M, layout, values)
nComparisons = size(values, 2);

x_ticks = reshape(layout.group_x', 1, []);
tick_labels = repmat(M.labels.group_short(:)', 1, nComparisons);

set(ax, 'XTick', x_ticks, ...
    'XTickLabel', tick_labels, ...
    'TickLabelInterpreter', 'none');

xlim(ax, [layout.x_min, layout.x_max]);
ylim(ax, computeSignedYLimits(values(:)));

yl = ylim(ax);
yr = diff(yl);

for c = 1:nComparisons
    text(ax, layout.comparison_center(c), yl(1) - 0.105 * yr, ...
        M.labels.comparison{c}, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'Interpreter', 'none', ...
        'FontSize', 10, ...
        'Clipping', 'off');
end

for c = 1:numel(layout.separator_x)
    plot(ax, [layout.separator_x(c), layout.separator_x(c)], yl, ...
        '-', 'Color', [0.75 0.75 0.75], ...
        'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
end

set(ax, 'Clipping', 'off');
end

function hfig = plotDeltaSummary( ...
    M, fig_visible, plot_style, group_colors_base, ...
    session_color_lightness_start, session_color_lightness_end, ...
    delta_sign_mode, ...
    point_size, point_alpha, ...
    bar_alpha, bar_value_mode, show_summary_marker, point_jitter_width, ...
    violin_alpha, show_mean_marker, show_median_line, ...
    draw_zero_line, zero_line_style, zero_line_width, ...
    use_broken_axis_for_delta, ...
    delta_break_start_prctile, ...
    delta_broken_axis_trigger_ratio, ...
    delta_tail_display_frac, ...
    delta_break_gap_frac, ...
    delta_min_tail_display_slope, ...
    draw_delta_broken_axis_marks, ...
    fig_width_min, fig_height, max_fig_width)

switch char(delta_sign_mode)
    case 'positive'
        delta_values = M.values.delta_positive_base;
        fig_name = 'Session delta summary: baseline >= 0';
        title_sign = 'base >= 0';
        ylabel_text = 'Delta, base >= 0';

    case 'negative'
        delta_values = M.values.delta_negative_base;
        fig_name = 'Session delta summary: baseline < 0';
        title_sign = 'base < 0';
        ylabel_text = 'Delta, base < 0';

    otherwise
        error('Unknown delta_sign_mode: %s', delta_sign_mode);
end

nSessions = size(delta_values, 1);
nComparisons = size(delta_values, 2);
nGroups = size(delta_values, 3);

layout = computeDeltaLayout(nComparisons, nGroups, nSessions);

fig_width = min(max_fig_width, ...
    max(fig_width_min, 90 * nComparisons * nGroups * nSessions + 240));

hfig = figure('Visible', fig_visible, ...
    'Color', 'w', ...
    'Position', [100 100 fig_width fig_height], ...
    'Name', fig_name);

ax = axes(hfig);
hold(ax, 'on');

set(ax, 'Units', 'normalized');
set(ax, 'Position', [0.055 0.25 0.92 0.66]);

group_colors = resolveGroupColors(group_colors_base, nGroups);
session_colors = makeSessionColorsByGroup( ...
    group_colors, nSessions, ...
    session_color_lightness_start, session_color_lightness_end);

num_items = nComparisons * nGroups * nSessions;
bar_width = computeAdaptiveItemWidth(num_items, 0.18, 0.52);
violin_width = computeAdaptiveItemWidth(num_items, 0.14, 0.42);

all_values = collectAllDeltaValues(delta_values);

delta_axis_info = computeSignedBrokenAxisInfo( ...
    all_values, ...
    use_broken_axis_for_delta, ...
    delta_break_start_prctile, ...
    delta_broken_axis_trigger_ratio, ...
    delta_tail_display_frac, ...
    delta_break_gap_frac, ...
    delta_min_tail_display_slope);

for c = 1:nComparisons
    for g = 1:nGroups
        for s = 1:nSessions
            x0 = layout.session_x(c, g, s);
            y = delta_values{s, c, g};
            color = squeeze(session_colors(g, s, :))';

            switch char(plot_style)
                case 'bar_points'
                    drawBarWithPoints(ax, x0, y, bar_width, color, ...
                        point_size, point_alpha, bar_alpha, ...
                        point_jitter_width, bar_value_mode, show_summary_marker, delta_axis_info);

                case 'violin'
                    drawViolinWithPoints(ax, x0, y, violin_width, color, ...
                        point_size, point_alpha, violin_alpha, ...
                        show_mean_marker, show_median_line, delta_axis_info);

                otherwise
                    error('Unknown plot_style: %s', plot_style);
            end
        end
    end
end

if draw_zero_line
    zero_plot = brokenTransformSigned(0, delta_axis_info);
    plot(ax, [layout.x_min, layout.x_max], [zero_plot, zero_plot], ...
        zero_line_style, ...
        'LineWidth', zero_line_width, ...
        'HandleVisibility', 'off');
end

applyDeltaAxisFormatting(ax, M, layout, delta_axis_info);

if delta_axis_info.use_broken_axis && draw_delta_broken_axis_marks
    drawYBrokenAxisMarks(ax, delta_axis_info);
end

title(ax, sprintf('%s | %s | %s | %s delta (%s)', ...
    M.meta.effect_type, M.meta.data_content, M.meta.model_mode, ...
    M.meta.metric_name, title_sign), ...
    'Interpreter', 'none', ...
    'FontWeight', 'bold');

ylabel(ax, ylabel_text, 'Interpreter', 'none');
xlabel(ax, '', 'Interpreter', 'none');

cleanAxis(ax);
end

function all_values = collectAllDeltaValues(delta_values)
all_values = [];

for i = 1:numel(delta_values)
    y = delta_values{i};
    y = y(:);
    y = y(isfinite(y));
    all_values = [all_values; y]; %#ok<AGROW>
end
end

function layout = computeDeltaLayout(nComparisons, nGroups, nSessions)
session_step = 0.78;
group_gap = 0.70;
comparison_gap = 1.25;

session_x = nan(nComparisons, nGroups, nSessions);
group_center = nan(nComparisons, nGroups);
comparison_center = nan(1, nComparisons);
separator_x = nan(1, max(0, nComparisons - 1));

x = 1;

for c = 1:nComparisons
    comp_first = x;

    for g = 1:nGroups
        group_first = x;

        for s = 1:nSessions
            session_x(c, g, s) = x;
            x = x + session_step;
        end

        group_last = session_x(c, g, nSessions);
        group_center(c, g) = mean([group_first, group_last]);

        if g < nGroups
            x = x + group_gap;
        end
    end

    comp_last = session_x(c, nGroups, nSessions);
    comparison_center(c) = mean([comp_first, comp_last]);

    if c < nComparisons
        separator_x(c) = comp_last + comparison_gap / 2;
    end

    x = x + comparison_gap;
end

layout.session_x = session_x;
layout.group_center = group_center;
layout.comparison_center = comparison_center;
layout.separator_x = separator_x;
layout.x_min = min(session_x(:)) - 0.7;
layout.x_max = max(session_x(:)) + 0.7;
end

function applyDeltaAxisFormatting(ax, M, layout, axis_info)
nSessions = M.meta.num_sessions;
nComparisons = M.meta.num_comparisons;
nGroups = M.meta.num_groups;

x_ticks = [];
tick_labels = {};

for c = 1:nComparisons
    for g = 1:nGroups
        for s = 1:nSessions
            x_ticks(end+1) = layout.session_x(c, g, s); %#ok<AGROW>
            tick_labels{end+1} = M.sessions.included(s).session_label; %#ok<AGROW>
        end
    end
end

set(ax, 'XTick', x_ticks, ...
    'XTickLabel', tick_labels, ...
    'TickLabelInterpreter', 'none');

xlim(ax, [layout.x_min, layout.x_max]);
ylim(ax, [axis_info.plot_axis_min, axis_info.plot_axis_max]);

set(ax, 'YTick', axis_info.plot_ticks, ...
    'YTickLabel', axis_info.tick_labels, ...
    'TickLabelInterpreter', 'none');

yl = ylim(ax);
yr = diff(yl);

group_text_y = yl(1) - 0.080 * yr;
comparison_text_y = yl(1) - 0.165 * yr;

for c = 1:nComparisons
    for g = 1:nGroups
        text(ax, layout.group_center(c, g), group_text_y, ...
            M.labels.group_short{g}, ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'top', ...
            'Interpreter', 'none', ...
            'FontSize', 9, ...
            'Clipping', 'off');
    end

    text(ax, layout.comparison_center(c), comparison_text_y, ...
        M.labels.comparison{c}, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'top', ...
        'Interpreter', 'none', ...
        'FontSize', 10, ...
        'Clipping', 'off');
end

for c = 1:numel(layout.separator_x)
    plot(ax, [layout.separator_x(c), layout.separator_x(c)], yl, ...
        '-', 'Color', [0.75 0.75 0.75], ...
        'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
end

set(ax, 'Clipping', 'off');
end

function w = computeAdaptiveItemWidth(num_items, min_w, max_w)
if num_items <= 0
    w = max_w;
    return;
end

w = 18 / max(num_items, 1);
w = max(min_w, min(max_w, w));
end

function colors = resolveGroupColors(group_colors_base, nGroups)
automatic_colors = lines(max(nGroups, 1));
colors = automatic_colors(1:nGroups, :);
nProvided = min(size(group_colors_base, 1), nGroups);

if nProvided > 0
    colors(1:nProvided, :) = group_colors_base(1:nProvided, :);
end
end

function session_colors = makeSessionColorsByGroup( ...
    group_colors, nSessions, light_start, light_end)

nGroups = size(group_colors, 1);
session_colors = nan(nGroups, nSessions, 3);

if nSessions == 1
    lightness = light_end;
else
    lightness = linspace(light_start, light_end, nSessions);
end

for g = 1:nGroups
    base = group_colors(g, :);

    for s = 1:nSessions
        f = lightness(s);
        c = (1 - f) * base + f * [1 1 1];
        session_colors(g, s, :) = c;
    end
end
end

function axis_info = makeLinearAxisInfo()
axis_info = struct();
axis_info.use_broken_axis = false;
axis_info.raw_axis_min = NaN;
axis_info.raw_axis_max = NaN;
axis_info.raw_abs_max = NaN;
axis_info.break_start = NaN;
axis_info.break_end = NaN;
axis_info.break_gap = 0;
axis_info.tail_display_len = 0;
axis_info.plot_axis_min = NaN;
axis_info.plot_axis_max = NaN;
axis_info.plot_ticks = [];
axis_info.tick_labels = {};
end

function drawBarWithPoints(ax, x0, y, width, color, point_size, point_alpha, ...
    bar_alpha, point_jitter_width, bar_value_mode, show_summary_marker, axis_info)

y = y(:);
y = y(isfinite(y));

if isempty(y)
    return;
end

meanVal = mean(y, 'omitnan');
medianVal = median(y, 'omitnan');

switch char(bar_value_mode)
    case 'mean'
        barVal = meanVal;
        markerVal = medianVal;
        markerShape = 's';

    case 'median'
        barVal = medianVal;
        markerVal = meanVal;
        markerShape = 's';

    otherwise
        error('Unknown bar_value_mode: %s', bar_value_mode);
end

barPlot = brokenTransformSigned(barVal, axis_info);
markerPlot = brokenTransformSigned(markerVal, axis_info);
zeroPlot = brokenTransformSigned(0, axis_info);
yPlot = brokenTransformSigned(y, axis_info);

hb = bar(ax, x0, barPlot, width, ...
    'FaceColor', color, ...
    'EdgeColor', color, ...
    'LineWidth', 0.8, ...
    'HandleVisibility', 'off');

try
    hb.BaseValue = zeroPlot;
catch
end

try
    hb.FaceAlpha = bar_alpha;
catch
end

if point_jitter_width > 0
    jitter = (rand(size(yPlot)) - 0.5) * point_jitter_width;
else
    jitter = zeros(size(yPlot));
end

try
    scatter(ax, x0 + jitter, yPlot, point_size, ...
        'MarkerFaceColor', color, ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceAlpha', point_alpha, ...
        'MarkerEdgeAlpha', point_alpha, ...
        'HandleVisibility', 'off');
catch
    scatter(ax, x0 + jitter, yPlot, point_size, ...
        'MarkerFaceColor', color, ...
        'MarkerEdgeColor', 'k', ...
        'HandleVisibility', 'off');
end

if show_summary_marker
    plot(ax, x0, markerPlot, markerShape, ...
        'MarkerSize', 6, ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', 'k', ...
        'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
end
end

function drawViolinWithPoints(ax, x0, y, width, color, point_size, point_alpha, ...
    violin_alpha, show_mean_marker, show_median_line, axis_info)

y = y(:);
y = y(isfinite(y));

if isempty(y)
    return;
end

if numel(y) >= 2 && (max(y) - min(y)) > eps
    [dens, yi] = estimateDensity(y);

    if ~isempty(dens) && max(dens) > 0
        dens = dens ./ max(dens) * width;
        yiPlot = brokenTransformSigned(yi, axis_info);

        patch(ax, [x0 - dens, fliplr(x0 + dens)], ...
            [yiPlot, fliplr(yiPlot)], color, ...
            'FaceAlpha', violin_alpha, ...
            'EdgeColor', color, ...
            'LineWidth', 0.8, ...
            'HandleVisibility', 'off');
    end
else
    yOne = brokenTransformSigned(y(1), axis_info);

    plot(ax, [x0 - width, x0 + width], [yOne, yOne], '-', ...
        'Color', color, ...
        'LineWidth', 1.4, ...
        'HandleVisibility', 'off');
end

yPlot = brokenTransformSigned(y, axis_info);
jitter = (rand(size(yPlot)) - 0.5) * width * 0.95;

try
    scatter(ax, x0 + jitter, yPlot, point_size, ...
        'MarkerFaceColor', color, ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceAlpha', point_alpha, ...
        'MarkerEdgeAlpha', point_alpha, ...
        'HandleVisibility', 'off');
catch
    scatter(ax, x0 + jitter, yPlot, point_size, ...
        'MarkerFaceColor', color, ...
        'MarkerEdgeColor', 'k', ...
        'HandleVisibility', 'off');
end

if show_median_line
    medVal = median(y, 'omitnan');
    medPlot = brokenTransformSigned(medVal, axis_info);

    plot(ax, [x0 - width * 0.72, x0 + width * 0.72], ...
        [medPlot, medPlot], ...
        'k-', ...
        'LineWidth', 1.0, ...
        'HandleVisibility', 'off');
end

if show_mean_marker
    meanVal = mean(y, 'omitnan');
    meanPlot = brokenTransformSigned(meanVal, axis_info);

    plot(ax, x0, meanPlot, 'kd', ...
        'MarkerSize', 5, ...
        'MarkerFaceColor', 'w', ...
        'LineWidth', 0.8, ...
        'HandleVisibility', 'off');
end
end

function [dens, yi] = estimateDensity(y)
y = y(:)';

if numel(y) < 2 || (max(y) - min(y)) <= eps
    dens = [];
    yi = [];
    return;
end

if exist('ksdensity', 'file') == 2
    try
        [dens, yi] = ksdensity(y, 'NumPoints', 80);
        dens = dens(:)';
        yi = yi(:)';
        return;
    catch
    end
end

nBins = min(24, max(6, round(sqrt(numel(y)) * 2)));
edges = linspace(min(y), max(y), nBins + 1);
counts = histcounts(y, edges);
centers = (edges(1:end-1) + edges(2:end)) / 2;

if numel(counts) >= 3
    kernel = [1 2 3 2 1];
    kernel = kernel / sum(kernel);
    counts = conv(counts, kernel, 'same');
end

yi = linspace(min(y), max(y), 80);
dens = interp1(centers, counts, yi, 'linear', 0);
end

function axis_info = computeSignedBrokenAxisInfo( ...
    values, use_broken_axis, break_start_prctile, ...
    trigger_ratio, tail_display_frac, break_gap_frac, min_tail_display_slope)

values = values(:);
values = values(isfinite(values));

axis_info = struct();
axis_info.use_broken_axis = false;
axis_info.break_start_prctile = break_start_prctile;
axis_info.trigger_ratio = trigger_ratio;
axis_info.tail_display_frac = tail_display_frac;
axis_info.break_gap_frac = break_gap_frac;
axis_info.min_tail_display_slope = min_tail_display_slope;
axis_info.raw_axis_min = NaN;
axis_info.raw_axis_max = NaN;
axis_info.raw_abs_max = NaN;
axis_info.break_start = NaN;
axis_info.break_end = NaN;
axis_info.break_gap = 0;
axis_info.tail_display_len = 0;
axis_info.plot_axis_min = NaN;
axis_info.plot_axis_max = NaN;
axis_info.plot_ticks = [];
axis_info.tick_labels = {};

if isempty(values)
    axis_info.raw_axis_min = -1;
    axis_info.raw_axis_max = 1;
    axis_info.raw_abs_max = 1;
    axis_info.break_start = 1;
    axis_info.break_end = 1;
    axis_info.plot_axis_min = -1;
    axis_info.plot_axis_max = 1;
    [axis_info.plot_ticks, axis_info.tick_labels] = buildLinearTicksAndLabels(-1, 1);
    return;
end

raw_min = min([values; 0]);
raw_max = max([values; 0]);
raw_abs_max = max(abs([raw_min, raw_max]));

if raw_abs_max <= 0 || ~isfinite(raw_abs_max)
    raw_abs_max = 1;
end

axis_info.raw_axis_min = raw_min;
axis_info.raw_axis_max = raw_max;
axis_info.raw_abs_max = raw_abs_max;

abs_vals = abs(values);
abs_vals = abs_vals(isfinite(abs_vals));

break_start = percentile_local(abs_vals, break_start_prctile);

if isempty(break_start) || ~isfinite(break_start) || break_start <= 0
    break_start = raw_abs_max;
end

do_broken = use_broken_axis && ...
    raw_abs_max > break_start * trigger_ratio && ...
    break_start > 0;

if ~do_broken
    axis_info.use_broken_axis = false;
    axis_info.break_start = raw_abs_max;
    axis_info.break_end = raw_abs_max;
    axis_info.break_gap = 0;
    axis_info.tail_display_len = 0;

    pad = 0.08 * max(eps, raw_max - raw_min);
    axis_info.plot_axis_min = raw_min - pad;
    axis_info.plot_axis_max = raw_max + pad;

    [axis_info.plot_ticks, axis_info.tick_labels] = ...
        buildLinearTicksAndLabels(axis_info.plot_axis_min, axis_info.plot_axis_max);

    return;
end

high_abs_vals = abs_vals(abs_vals > break_start);
break_end = min(high_abs_vals);

if isempty(break_end) || ~isfinite(break_end) || break_end <= break_start
    break_end = break_start;
end

raw_tail_span = max(eps, raw_abs_max - break_end);
tail_display_len_from_frac = max(eps, break_start * tail_display_frac);
tail_display_len_from_slope = raw_tail_span * min_tail_display_slope;
tail_display_len = max(tail_display_len_from_frac, tail_display_len_from_slope);
break_gap = max(eps, break_start * break_gap_frac);

axis_info.use_broken_axis = true;
axis_info.break_start = break_start;
axis_info.break_end = break_end;
axis_info.break_gap = break_gap;
axis_info.tail_display_len = tail_display_len;

plot_min = brokenTransformSigned(raw_min, axis_info);
plot_max = brokenTransformSigned(raw_max, axis_info);

pad = 0.08 * max(eps, plot_max - plot_min);

axis_info.plot_axis_min = plot_min - pad;
axis_info.plot_axis_max = plot_max + pad;

[axis_info.plot_ticks, axis_info.tick_labels] = buildBrokenTicksAndLabels(axis_info);
end

function x_plot = brokenTransformSigned(x_raw, axis_info)
x_plot = x_raw;

if ~isfield(axis_info, 'use_broken_axis') || ~axis_info.use_broken_axis
    return;
end

sgn = sign(x_raw);
ax = abs(x_raw);

break_start = axis_info.break_start;
break_end = axis_info.break_end;
raw_abs_max = axis_info.raw_abs_max;
tail_display_len = axis_info.tail_display_len;
break_gap = axis_info.break_gap;

x_plot_abs = ax;

gap_mask = ax > break_start & ax < break_end;
tail_mask = ax >= break_end;

if break_end > break_start
    x_plot_abs(gap_mask) = break_start ...
        + (ax(gap_mask) - break_start) ./ (break_end - break_start) .* break_gap;
else
    x_plot_abs(gap_mask) = break_start + break_gap;
end

if raw_abs_max > break_end
    x_plot_abs(tail_mask) = break_start + break_gap ...
        + (ax(tail_mask) - break_end) ./ (raw_abs_max - break_end) .* tail_display_len;
else
    x_plot_abs(tail_mask) = break_start + break_gap + tail_display_len;
end

x_plot = sgn .* x_plot_abs;
end

function [ticks, labels] = buildLinearTicksAndLabels(axis_min, axis_max)
if ~isfinite(axis_min) || ~isfinite(axis_max) || axis_min == axis_max
    axis_min = -1;
    axis_max = 1;
end

ticks = linspace(axis_min, axis_max, 5);
ticks(abs(ticks) < 1e-12) = 0;
labels = composeNumericTickLabels(ticks);
end

function [plot_ticks, tick_labels] = buildBrokenTicksAndLabels(axis_info)
raw_ticks = choosePrebreakTicksSigned(axis_info.break_start);

raw_ticks = raw_ticks(raw_ticks >= axis_info.raw_axis_min & ...
    raw_ticks <= axis_info.raw_axis_max);

if ~any(abs(raw_ticks) < 1e-12)
    raw_ticks = sort([raw_ticks, 0]);
end

raw_ticks = uniqueWithTolerance(raw_ticks, 1e-10);
plot_ticks = brokenTransformSigned(raw_ticks, axis_info);
tick_labels = composeNumericTickLabels(raw_ticks);
end

function raw_ticks = choosePrebreakTicksSigned(prebreak_abs_max)
if isempty(prebreak_abs_max) || ~isfinite(prebreak_abs_max) || prebreak_abs_max <= 0
    raw_ticks = 0;
    return;
end

target_intervals = 4;
rough_step = (2 * prebreak_abs_max) / target_intervals;
step = chooseNiceNumericStep(rough_step);

if step <= 0 || ~isfinite(step)
    raw_ticks = linspace(-prebreak_abs_max, prebreak_abs_max, 5);
    raw_ticks(abs(raw_ticks) < 1e-12) = 0;
    return;
end

max_tick = floor(prebreak_abs_max / step) * step;

if max_tick <= 0
    raw_ticks = [-prebreak_abs_max, 0, prebreak_abs_max];
else
    raw_ticks = -max_tick:step:max_tick;

    if ~any(abs(raw_ticks) < 1e-12)
        raw_ticks = sort([raw_ticks, 0]);
    end
end

raw_ticks(abs(raw_ticks) < 1e-12) = 0;
end

function step = chooseNiceNumericStep(rough_step)
if rough_step <= 0 || ~isfinite(rough_step)
    step = 1;
    return;
end

exponent = floor(log10(rough_step));
base = 10 ^ exponent;
candidates = [1 2 2.5 5 10] * base;
candidates = candidates(candidates >= rough_step);

if isempty(candidates)
    step = 10 * base;
else
    step = candidates(1);
end
end

function vals_unique = uniqueWithTolerance(vals, tol)
vals = vals(:)';
vals_unique = [];

for i = 1:numel(vals)
    if isempty(vals_unique) || all(abs(vals(i) - vals_unique) > tol)
        vals_unique(end+1) = vals(i); %#ok<AGROW>
    end
end
end

function labels = composeNumericTickLabels(vals)
labels = cell(size(vals));

for i = 1:numel(vals)
    v = vals(i);

    if abs(v) < 1e-12
        v = 0;
    end

    if abs(v) >= 1000 || (abs(v) > 0 && abs(v) < 0.001)
        labels{i} = sprintf('%.2g', v);
    elseif abs(v - round(v)) < 1e-10
        labels{i} = sprintf('%d', round(v));
    else
        labels{i} = sprintf('%.3g', v);
    end
end
end

function drawYBrokenAxisMarks(ax, axis_info)
if ~axis_info.use_broken_axis
    return;
end

xLim = ax.XLim;
yLim = ax.YLim;

xSpan = max(eps, diff(xLim));
ySpan = max(eps, diff(yLim));

% Use x-axis scale only for horizontal slash width,
% and y-axis scale only for vertical slash height.
% Do not use max(xSpan, ySpan), otherwise a wide x-axis makes the
% y-axis break marks extremely large.
slash_dx = xSpan * 0.006;
slash_dy = ySpan * 0.018;
offset_y = ySpan * 0.018;

x0 = xLim(1);

break_center_abs = axis_info.break_start + axis_info.break_gap / 2;

y_centers = [];

if axis_info.raw_axis_max > axis_info.break_start
    y_centers(end+1) = break_center_abs; 
end

if axis_info.raw_axis_min < -axis_info.break_start
    y_centers(end+1) = -break_center_abs; 
end

for i = 1:numel(y_centers)
    yc = y_centers(i);

    % First slash.
    plot(ax, ...
        [x0 - slash_dx, x0 + slash_dx], ...
        [yc - slash_dy, yc + slash_dy], ...
        'k-', ...
        'LineWidth', 1.0, ...
        'Clipping', 'off', ...
        'HandleVisibility', 'off');

    % Second slash.
    plot(ax, ...
        [x0 - slash_dx, x0 + slash_dx], ...
        [yc - slash_dy + offset_y, yc + slash_dy + offset_y], ...
        'k-', ...
        'LineWidth', 1.0, ...
        'Clipping', 'off', ...
        'HandleVisibility', 'off');
end
end

function q = percentile_local(x, p)
x = x(:);
x = x(isfinite(x));

if isempty(x)
    q = NaN;
    return;
end

x = sort(x);
n = numel(x);

if n == 1
    q = x;
    return;
end

p = max(0, min(100, p));
pos = 1 + (n - 1) * p / 100;

lo = floor(pos);
hi = ceil(pos);

if lo == hi
    q = x(lo);
else
    w = pos - lo;
    q = (1 - w) * x(lo) + w * x(hi);
end
end

function yLim = computeSignedYLimits(values)
values = values(:);
values = values(isfinite(values));

if isempty(values)
    yLim = [-1 1];
    return;
end

vmin = min(values);
vmax = max(values);

vmin = min(vmin, 0);
vmax = max(vmax, 0);

if abs(vmax - vmin) < eps
    if vmax == 0
        yLim = [-1 1];
    else
        pad = abs(vmax) * 0.1;
        yLim = [vmin - pad, vmax + pad];
    end

    return;
end

pad = 0.10 * (vmax - vmin);
yLim = [vmin - pad, vmax + pad];
end

function cleanAxis(ax)
grid(ax, 'on');
box(ax, 'off');

set(ax, ...
    'TickDir', 'out', ...
    'LineWidth', 1, ...
    'FontSize', 11);
end

function label = makeComparisonLabel(baseline_field, comparation_field)
label = sprintf('%s v %s', ...
    shortFieldLabel(comparation_field), ...
    shortFieldLabel(baseline_field));
end

function label = shortFieldLabel(field_name)
switch char(field_name)
    case 'y'
        label = 'y';

    case 'd'
        label = 'd';

    case 'yRecon_use_all'
        label = 'all';

    case 'yRecon_use_all_no_d'
        label = 'all no d';

    case 'yRecon_use_across'
        label = 'acr';

    case 'yRecon_use_across_no_d'
        label = 'acr no d';

    case 'yRecon_use_within'
        label = 'win';

    case 'yRecon_use_within_no_d'
        label = 'win no d';

    case 'yRecon_across_excl_within'
        label = 'acr excl win';

    case 'yRecon_within_excl_across'
        label = 'win excl acr';

    case 'yRecon_use_feedback'
        label = 'fb';

    case 'yRecon_feedback_excl_within_ff_ambiguous'
        label = 'fb excl win ff amb';

    case 'yRecon_feedback_excl_within'
        label = 'fb excl win';

    case 'yRecon_feedback_excl_ff_ambiguous'
        label = 'fb excl ff amb';

    case 'yRecon_use_feedforward'
        label = 'ff';

    case 'yRecon_feedforward_excl_within_fb_ambiguous'
        label = 'ff excl win fb amb';

    case 'yRecon_feedforward_excl_within'
        label = 'ff excl win';

    case 'yRecon_feedforward_excl_fb_ambiguous'
        label = 'ff excl fb amb';

    case 'yRecon_use_all_with_R'
        label = 'all R';

    case 'yRecon_use_across_with_R'
        label = 'acr R';

    case 'yRecon_use_within_with_R'
        label = 'win R';

    case 'yRecon_across_excl_within_with_R'
        label = 'acr excl win R';

    case 'yRecon_within_excl_across_with_R'
        label = 'win excl acr R';

    case 'yRecon_use_all_keep_resid'
        label = 'all KR';

    case 'yRecon_use_across_keep_resid'
        label = 'acr KR';

    case 'yRecon_use_within_keep_resid'
        label = 'win KR';

    case 'yRecon_across_excl_within_keep_resid'
        label = 'acr excl win KR';

    case 'yRecon_within_excl_across_keep_resid'
        label = 'win excl acr KR';

    otherwise
        label = fallbackShortFieldLabel(field_name);
end
end

function label = fallbackShortFieldLabel(field_name)
label = char(field_name);

label = strrep(label, 'yRecon_', '');
label = strrep(label, 'use_', '');
label = strrep(label, 'across', 'acr');
label = strrep(label, 'within', 'win');
label = strrep(label, 'excl', 'excl');
label = strrep(label, 'feedback', 'fb');
label = strrep(label, 'feedforward', 'ff');
label = strrep(label, 'ambiguous', 'amb');
label = strrep(label, 'condition', 'cond');
label = strrep(label, 'residual', 'resid');
label = strrep(label, 'resid', 'res');
label = strrep(label, '_', ' ');
label = regexprep(label, '\s+', ' ');
label = strtrim(label);
end

function savePngLocal(fig, pngFile, dpi)
drawnow;

try
    if exist('exportgraphics', 'file') == 2
        exportgraphics(fig, pngFile, ...
            'Resolution', dpi, ...
            'BackgroundColor', 'white');
    else
        set(fig, 'PaperPositionMode', 'auto');
        print(fig, pngFile, '-dpng', sprintf('-r%d', dpi));
    end
catch
    warning('exportgraphics/print failed. Falling back to saveas.');
    saveas(fig, pngFile);
end
end
